database:
  name: "workerunion"
  username: "fangchao"
  password: "123456"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

jwt:
  secret: "owhefowfow"
  expire_hour: 720

redis:
  port: "6379"
  host: "localhost"

email:
  server: "smtp.office365.com"
  port: 587
  username: "workerunion@outlook.com"
  password: "fangchao1994."